CREATE TABLE public.positions (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    latitude FLOAT8 NOT NULL,
    longitude FLOAT8 NOT NULL,
    speed FLOAT4,
    power FLOAT4,
    odometer FLOAT4,
    ideal_battery_range_km FLOAT4,
    battery_level INT2,
    outside_temp FLOAT4,
    elevation INT2,
    fan_status INT4,
    driver_temp_setting FLOAT4,
    passenger_temp_setting FLOAT4,
    is_climate_on BOOLEAN,
    is_rear_defroster_on BOOLEAN,
    is_front_defroster_on BOOLEAN,
    car_id INT2 NOT NULL,
    drive_id INT4,
    inside_temp FLOAT4,
    battery_heater BOOLEAN,
    battery_heater_on BOOLEAN,
    battery_heater_no_power BOOLEAN,
    est_battery_range_km FLOAT4,
    rated_battery_range_km FLOAT4,
    usable_battery_level INT2,
    tpms_pressure_fl FLOAT4,
    tpms_pressure_fr FLOAT4,
    tpms_pressure_rl FLOAT4,
    tpms_pressure_rr FLOAT4
);
