-- CREATE USER grafana WITH PASSWORD 'grafana';
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grafana;

DO $$
BEGIN
-- CREATE ROLE rafana;
CREATE USER grafana WITH PASSWORD 'grafana';
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grafana;
EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
END
$$;
