version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    volumes:
      # NOTE: Set the pgadmin directory owner to uid 5050
      - ./chipmunk_docker/postgres:/var/lib/postgresql/data:Z
    networks:
      - chipmunk_internal
    environment:
      POSTGRES_USER: chipmunk
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: chipmunk

  chipmunk:
    image: chipmunk
    build: .
    container_name: chipmunk
    hostname: chipmunk
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}" # Chipmunk
      - "3073:3000" # Grafana
    depends_on:
      - db
    volumes:
      # NOTE: Set the grafana directory owner to 472:0
      - ./chipmunk_docker/grafana:/var/lib/grafana:Z
    networks:
      - chipmunk_internal
    environment:
      TZ: America/Los_Angeles
      DATABASE_USER: grafana
      DATABASE_PASS: grafana
      DATABASE_NAME: chipmunk
      DATABASE_HOST: db
      RUST_LOG: info,sqlx::query=warn,tungstenite=info,reqwest=warn,hyper=warn #,warp=warn
      TOKEN_ENCRYPTION_KEY: ${TOKEN_ENCRYPTION_KEY} # This comes from the .env file
      # Postgres URL format: postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
      DATABASE_URL: "postgres://chipmunk:${DATABASE_PASSWORD}@db:5432/chipmunk"

networks:
  chipmunk_internal: