on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

name: CI

env:
  CARGO_TERM_COLOR: always
  TOKEN_ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef
  DATABASE_PASSWORD: secret_password
  DATABASE_URL: postgres://chipmunk:secret_password@localhost:5432/chipmunk
  TEST_DATABASE_URL: postgres://chipmunk:secret_password@localhost:5432/chipmunk
  HTTP_PORT: 3072
  SQLX_OFFLINE: true
  RUST_LOG: debug,sqlx::query=warn,tungstenite=info,reqwest=warn,hyper=warn,warp=debug

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
        with:
          # By default, actions/checkout checks out a merge commit. Check out the PR head instead.
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-01-20
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
        with:
          cache-on-failure: "true"
      - name: Lint (clippy)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets
      - name: Lint (clippy) frontend
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets --manifest-path ui/frontend/Cargo.toml
      - name: Lint (rustfmt)
        uses: actions-rs/cargo@v1
        if: always()
        with:
          command: fmt
          args: --check
      - name: Lint (rustfmt) frontend
        uses: actions-rs/cargo@v1
        if: always()
        with:
          command: fmt
          args: --check --manifest-path ui/frontend/Cargo.toml

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        rust-version: [ nightly-2024-01-20 ]
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
    services:
      db:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: chipmunk
          POSTGRES_PASSWORD: secret_password
          POSTGRES_DB: chipmunk
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
        with:
          cache-on-failure: "true"
      - name: Build all targets with all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features
      - name: Frontend
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features --manifest-path ui/frontend/Cargo.toml
      - name: Doctests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features
      - name: Doctests on frontend
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features --manifest-path ui/frontend/Cargo.toml
      - name: Running containers
        run: docker ps -a
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Test with nextest
        run: |
          set -e
          mkdir -p target/debug/deps/dist/
          touch target/debug/deps/dist/index.html
          mkdir -p chipmunk/target/dist
          touch chipmunk/target/dist/index.html
          mkdir -p /home/runner/work/chipmunk/chipmunk/target/dist
          touch /home/runner/work/chipmunk/chipmunk/target/dist/index.html
          cargo nextest run
          cd ui/frontend
          cargo nextest run
