on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

name: CI

env:
  CARGO_TERM_COLOR: always
  TOKEN_ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef
  DATABASE_PASSWORD: secret_password
  DATABASE_URL: postgres://chipmunk:secret_password@db:5432/chipmunk
  HTTP_PORT: 3072
  SQLX_OFFLINE: true
  RUST_LOG: debug

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
        with:
          # By default actions/checkout checks out a merge commit. Check out the PR head instead.
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-01-20
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - name: Lint (clippy)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets
      - name: Lint (rustfmt)
        uses: actions-rs/cargo@v1
        if: always()
        with:
          command: fmt
          args: --check
      # - name: Install cargo readme
      #   uses: baptiste0928/cargo-install@v1
      #   with:
      #     crate: cargo-readme
      #     version: latest
      # - name: Run cargo readme
      #   run: ./scripts/regenerate-readmes.sh
      # - name: Check for differences
      #   run: git diff --exit-code

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        rust-version: [ nightly-2024-01-20 ]
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # - uses: actions-rs/toolchain@v1
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
     # - name: Build all targets with all features
     #   uses: actions-rs/cargo@v1
     #   with:
     #     command: build
     #     args: --all-targets --all-features
     # - name: Doctests
     #   uses: actions-rs/cargo@v1
     #   with:
     #     command: test
     #     args: --doc --all-features
      - name: Starting database container
        run: docker compose -f docker-compose.yml run --rm --service-ports --detach --name db db
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Test with nextest
        run: cargo nextest run
      - name: Another way of testing
        if: always()
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run
